title: "Conscience Morte"
description: "Journal de laboratoire consacré aux formes de vie artificielles."
lang: fr

url: "https://consciencemorte.github.io"
baseurl: ""
permalink: /observations/:title/

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  notes:
    output: true
    permalink: /notes/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: notes
    values:
      layout: note

sass:
  sass_dir: assets

exclude:
  - README.md
  - Gemfile.lock
  - old_archive
